### ISSUE TITLE
Value is not a table and has no __newindex meta method.

### ISSUE THREAD

**Issue by jeff-emanuel** [milochristiansen/lua#12] opened 2018-04-25 17:02 UTC
I get this running the same code as posted for issue 11 after updating with that fix.

panic: Value is not a table and has no __newindex meta method.

goroutine 1 [running]:
github.com/milochristiansen/lua/luautil.Raise(0x527701, 0x37, 0x4)
        c:/dev/go/src/github.com/milochristiansen/lua/luautil/errors.go:82 +0xa0
github.com/milochristiansen/lua.(*State).setTable(0xc0420340e0, 0x0, 0x0, 0x4f7ca0, 0xc042009998, 0x4f7ca0, 0xc0420ca520)
        c:/dev/go/src/github.com/milochristiansen/lua/value.go:363 +0x29d
github.com/milochristiansen/lua.init.1.func11(0xc0420340e0, 0xc00201c14a, 0xc042010f00)
        c:/dev/go/src/github.com/milochristiansen/lua/vm.go:193 +0xfb
github.com/milochristiansen/lua.(*State).exec(0xc0420340e0)
        c:/dev/go/src/github.com/milochristiansen/lua/vm.go:81 +0x129
github.com/milochristiansen/lua.(*State).call(0xc0420340e0, 0x0, 0x0, 0x0, 0xc042002800)
        c:/dev/go/src/github.com/milochristiansen/lua/vm.go:66 +0x109
github.com/milochristiansen/lua.(*State).Call(0xc0420340e0, 0x0, 0x0)
        c:/dev/go/src/github.com/milochristiansen/lua/api.go:1014 +0x5c
main.main()

**Comment by milochristiansen** [comment] 2018-04-25 17:05
Hmm. Damn. I was sure I got a clean run when I tested it, but I guess not. I'll track it down and have it fixed shortly.

**Comment by jeff-emanuel** [comment] 2018-04-25 17:06
It works for a shorter array.  I'm trying to find the limit now.

**Comment by jeff-emanuel** [comment] 2018-04-25 17:13
I'm getting failure for an array greater than about 288 elements.

This works:

forward = {
	137, 176, 178, 181, 189, 193, 196, 197, 204, 205, 210, 211, 213, 215,
 218, 218, 221, 222, 222, 223, 224, 225, 228, 229, 230, 241, 241, 242, 243, 247,
 254, 255, 256, 258, 258, 266, 278, 280, 282, 288, 296, 299, 299, 301, 303, 305,
 306, 306, 310, 310, 313, 315, 319, 320, 321, 322, 323, 327, 328, 332, 335, 340,
 343, 344, 345, 348, 349, 352, 354, 357, 358, 358, 359, 360, 362, 362, 363, 365,
 366, 368, 368, 369, 370, 371, 372, 373, 375, 376, 376, 377, 381, 381, 382, 384,
 385, 386, 387, 388, 389, 390, 391, 392, 392, 393, 395, 396, 397, 399, 399, 400,
 400, 401, 402, 403, 404, 405, 407, 408, 409, 410, 411, 412, 412, 414, 414, 415,
 415, 416, 416, 417, 418, 420, 420, 421, 421, 422, 423, 425, 426, 427, 428, 429,
 430, 431, 432, 433, 434, 435, 437, 437, 438, 438, 439, 440, 441, 442, 443, 444,
 445, 610, 623, 623, 627, 627, 628, 629, 630, 641, 653, 655, 656, 656, 656, 659,
 661, 661, 662, 664, 666, 670, 678, 682, 690, 698, 700, 702, 703, 704, 704, 712,
 716, 719, 720, 725, 726, 727, 733, 734, 735, 739, 740, 742, 743, 745, 746, 749,
 753, 754, 755, 758, 759, 760, 761, 765, 767, 768, 775, 776, 777, 778, 780, 781,
 783, 784, 784, 785, 786, 787, 790, 792, 794, 796, 796, 799, 800, 800, 800, 801,
 803, 805, 806, 808, 808, 809, 811, 814, 815, 816, 817, 819, 821, 822, 827, 828,
 829, 830, 832, 833, 835, 836, 837, 838, 839, 840, 841, 842, 843, 844, 846, 847,
 853, 854, 856, 857, 859, 860, 861, 862, 862,
 5453, 5474, 5475, 5476, 5487, 5488, 5489, 5490, 5491}

This doesn't:

forward = {
	137, 176, 178, 181, 189, 193, 196, 197, 204, 205, 210, 211, 213, 215,
 218, 218, 221, 222, 222, 223, 224, 225, 228, 229, 230, 241, 241, 242, 243, 247,
 254, 255, 256, 258, 258, 266, 278, 280, 282, 288, 296, 299, 299, 301, 303, 305,
 306, 306, 310, 310, 313, 315, 319, 320, 321, 322, 323, 327, 328, 332, 335, 340,
 343, 344, 345, 348, 349, 352, 354, 357, 358, 358, 359, 360, 362, 362, 363, 365,
 366, 368, 368, 369, 370, 371, 372, 373, 375, 376, 376, 377, 381, 381, 382, 384,
 385, 386, 387, 388, 389, 390, 391, 392, 392, 393, 395, 396, 397, 399, 399, 400,
 400, 401, 402, 403, 404, 405, 407, 408, 409, 410, 411, 412, 412, 414, 414, 415,
 415, 416, 416, 417, 418, 420, 420, 421, 421, 422, 423, 425, 426, 427, 428, 429,
 430, 431, 432, 433, 434, 435, 437, 437, 438, 438, 439, 440, 441, 442, 443, 444,
 445, 610, 623, 623, 627, 627, 628, 629, 630, 641, 653, 655, 656, 656, 656, 659,
 661, 661, 662, 664, 666, 670, 678, 682, 690, 698, 700, 702, 703, 704, 704, 712,
 716, 719, 720, 725, 726, 727, 733, 734, 735, 739, 740, 742, 743, 745, 746, 749,
 753, 754, 755, 758, 759, 760, 761, 765, 767, 768, 775, 776, 777, 778, 780, 781,
 783, 784, 784, 785, 786, 787, 790, 792, 794, 796, 796, 799, 800, 800, 800, 801,
 803, 805, 806, 808, 808, 809, 811, 814, 815, 816, 817, 819, 821, 822, 827, 828,
 829, 830, 832, 833, 835, 836, 837, 838, 839, 840, 841, 842, 843, 844, 846, 847,
 853, 854, 856, 857, 859, 860, 861, 862, 862, 863,
 5453, 5474, 5475, 5476, 5487, 5488, 5489, 5490, 5491}

**Comment by milochristiansen** [comment] 2018-04-25 17:51
I can see the issue in the generated code (a register is being clobbered), but I am not sure exactly where the bad instructions are being generated. I think I know of at least one place where it may be wrong, so I have a good place to start at least.

EDIT: 288? That is oddly specific... Thank you, I'm sure that will help.

**Comment by milochristiansen** [comment] 2018-04-25 18:26
Try that. I goofed and didn't increment the register properly when loading constants in certain cases, hopefully it is fixed now.

There may still be other issues in there, but my simple test was clean... I need to spend a bit more time examining this in the future regardless of whether this fixes your issue or not.

**Comment by jeff-emanuel** [comment] 2018-04-25 18:30
Array of length 295 works.  An array of length 3848 panics:

panic: runtime error: makeslice: len out of range

goroutine 1 [running]:
github.com/milochristiansen/lua.(*table).extend(0xc04203c240, 0x670)
        c:/dev/go/src/github.com/milochristiansen/lua/table.go:69 +0x6a
github.com/milochristiansen/lua.(*table).maybeExtend(0xc04203c240, 0xcdd, 0x407b05)
        c:/dev/go/src/github.com/milochristiansen/lua/table.go:145 +0x2e4
github.com/milochristiansen/lua.(*table).setInt(0xc04203c240, 0xcde, 0x4f7b80, 0xc0422cb3d0)
        c:/dev/go/src/github.com/milochristiansen/lua/table.go:169 +0x225
github.com/milochristiansen/lua.(*table).SetRaw(0xc04203c240, 0x4f7b80, 0xc0422211c8, 0x4f7b80, 0xc0422cb3d0)
        c:/dev/go/src/github.com/milochristiansen/lua/table.go:256 +0x29e
github.com/milochristiansen/lua.(*State).setTable(0xc04206e070, 0x510600, 0xc04203c240, 0x4f7b80, 0xc0422211c8, 0x4f7b80, 0xc0422cb3d0)
        c:/dev/go/src/github.com/milochristiansen/lua/value.go:336 +0x2b8
github.com/milochristiansen/lua.init.1.func11(0xc04206e070, 0xc00202014a, 0xc04206ae00)
        c:/dev/go/src/github.com/milochristiansen/lua/vm.go:193 +0xfb
github.com/milochristiansen/lua.(*State).exec(0xc04206e070)
        c:/dev/go/src/github.com/milochristiansen/lua/vm.go:81 +0x129
github.com/milochristiansen/lua.(*State).call(0xc04206e070, 0x0, 0x0, 0x0, 0xc042054400)
        c:/dev/go/src/github.com/milochristiansen/lua/vm.go:66 +0x109
github.com/milochristiansen/lua.(*State).Call(0xc04206e070, 0x0, 0x0)
        c:/dev/go/src/github.com/milochristiansen/lua/api.go:1014 +0x5c
main.main()

**Comment by jeff-emanuel** [comment] 2018-04-25 18:34
Length 1917 works, 1918 fails.

**Comment by milochristiansen** [comment] 2018-04-25 18:41
Well, I'm pretty sure this is not caused by constant overflows or register clobbering, so... Uh, congratulations? on finding three bugs in one feature. You are probably the first person to use giant constant tables.

I'm tracing the problem code right now.

**Comment by jeff-emanuel** [comment] 2018-04-25 18:46
My real code doesn't use giant constant tables, but this panic is the same that the real code encounters.

**Comment by milochristiansen** [comment] 2018-04-25 19:14
Cannot reproduce with the following Lua code:
```
forward = {
	-- Constant numbers from 1 to 2000
}
reverse = {}
for i,v in ipairs(forward) do
	reverse[v] = i
end

**Comment by jeff-emanuel** [comment] 2018-04-25 19:19
Try this
[reverseluaarray.zip](https://github.com/milochristiansen/lua/files/1948525/reverseluaarray.zip)

**Comment by milochristiansen** [comment] 2018-04-25 19:25
That did the trick quite nicely, which actually gives me some idea of what is wrong. Since your sequence starts quite a ways from 1, it leads me to believe there is an issue in the code that handles switching from storing in the hash portion to the array portion. This would help explain the odd table lengths at which it suddenly stops working.

**Comment by milochristiansen** [comment] 2018-04-25 20:24
Ok, does that do it? It fixes the test case at least, but does it solve your real issue?

**Comment by milochristiansen** [comment] 2018-04-25 21:01
The test suite is failing now BTW, so even if your issue is fixed (I hope it is), it seems I broke something else in the process.

**Comment by jeff-emanuel** [comment] 2018-04-25 23:32
This test and a test that more closely resembles my real code both run without panics now.  Thanks a bunch!

**Closed as completed** 2018-04-26 01:15 UTC
